source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SimpleTransition_Example' do
  pod "SimpleTransition", :path => "../"
end

target 'SimpleTransition_Tests' do
  pod "SimpleTransition", :path => "../"

  pod 'Quick'
  pod 'Nimble'
end

# post install
post_install do |installer|
    # Build settings
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
